# Prerequisites
# A Nerd Font installed and enabled in your terminal.
#
# test with:
# echo -e "\ue795  \ue73c  \uf1d6  \uf126  \uf489"

format = """
â•­â”€${all}${line_break}\
â”‚${fill}${directory}${custom.git_host}${time}${line_break}\
â•°â”€${character}"""
#$localip\
#$git_branch\
#$git_status\

[cmd_duration]
#format = '[$duration]($style) '
#min_time = 0
min_time_to_notify = 300000
show_notifications = true

[directory]
repo_root_style = "bright-red"
style = "red"
truncate_to_repo = false 
truncation_length = 8
truncation_symbol = 'â€¦/'
#before_repo_root_style = "bold blue"

[fill]
symbol = " "

[gcloud]
symbol = "îŸ° "

[hostname]
format = '[$hostname$ssh_symbol]($style) '
ssh_only = false
ssh_symbol = " ðŸŒ"
style = "bright-blue"

[nodejs]
symbol = "îµ„ "

[php]
symbol = "îµ­ "

[python]
symbol = "î´› "

[time]
disabled = false
format = '[\[$time\]]($style) '
style = "blue"

[username]
format = '[$user@]($style)'
show_always = true
style_root = "bold green"
style_user = "bright-green"


[custom.git_host]
# This command checks the remote URL and outputs the corresponding icon
command = """
url=$(git config --get remote.origin.url 2> /dev/null)
if [[ "$url" =~ "github" ]]; then
    echo "îª„"
elif [[ "$url" =~ "gitlab" ]]; then
    echo "ó°® "
elif [[ "$url" =~ "bitbucket" ]]; then
    echo "ï…±"
elif [[ -n "$url" ]]; then
    echo "ï‡“"
fi
"""
# Only run this command if we are inside a git directory
when = "git rev-parse --is-inside-work-tree 2> /dev/null"
# Run inside a shell that supports standard conditionals
shell = ["bash", "--noprofile", "--norc"] 
style = "bold #f14e32" # You can change this color
format = "[$output]($style) "
description = "Shows whether the remote is GitHub, GitLab, or Bitbucket"
